memcache/sharded_client.go
To avoid goroutines from getting stuck on the channel and having to sleep/wakeup
=> Use buffered channels in memcache sharded_client

.travis.yml, database/binlog/rows_event_test.go, database/binlog/string_fields.go, database/binlog/string_fields_test.go
MySQL doc - http://dev.mysql.com/doc/refman/5.0/en/binary-varbinary.html
=> Pad fixed-length binary columns values similar to what MySQL does

database/binlog/mock_log_file.go
=> binlog: Add support to write Previous GTID event and GTID event to mock log file

cinterop/test/batched/example_batched.go, cinterop/test/buffered/example_buffered.go, cinterop/test/client.go, cinterop/test/unbuffered/example.go, container/set/set.go, database/binlog/log_file_event_reader_test.go, database/binlog/log_stream_event_reader_test.go, database/binlog/mock_log_file.go, database/binlog/numeric_fields_test.go, database/binlog/parsed_event_reader_test.go, database/binlog/query_event_test.go, database/binlog/raw_event_reader_test.go, database/binlog/table_map_event_test.go, database/sqltypes/sqltypes.go, sort2/sort_test.go
Courtesy goimports:
http://godoc.org/golang.org/x/tools/cmd/goimports
=> Cleanup imports and formatting.

caching/generic_storage.go, cinterop/maximally_batched_work.go, cinterop/server.go, container/set/set.go, container/set/set_test.go, database/binlog/temporal_fields.go, database/sqlbuilder/column.go, database/sqlbuilder/expression.go, database/sqlbuilder/table.go, database/sqltypes/sqltypes.go, errors/errors.go
As suggested by golint:
https://github.com/golang/lint
Not exhaustive by any means, more me testing the tool.
=> Misc fixes and cleanups, no functional changes.

net2/http2/load_balanced_pool.go
=> Revert "Only make pool for each unique instanceInfo Addr"

net2/http2/load_balanced_pool.go
Only create connections to unique hosts
Reuse connections from the previous run if they are to the same hosts
=> Only make pool for each unique instanceInfo Addr

math2/rand2/rand.go
this ensures third party packages also benefit from the change.
=> Use math/rand's global random generator instead of creating a new one

math2/rand2/rand.go
msolo is testing my vim regex-fu
:'<,'>s/func \(.*\)(.*(.*$/\1 = rand.\1
=> simplify rand2

README.md, math2/rand2/rand.go
We have many jitter implementations.  time to consolidate.
=> Consolidate jitteriness.

container/concurrent/doc.go, container/concurrent/lrucache.go, container/concurrent/lrucache_test.go, container/concurrent/map.go, container/concurrent/map_test.go, container/lrucache/lrucache.go, container/lrucache/lrucache_test.go
- Adding thread-safe versions of LRU cache and map
- Adding Delete functionality to LRU cache
=> Adding thread-safe versions for LRU cache and map

container/concurrent/map.go
Missed this in the last commit!
=> Fix defer bug with thread-safe map

database/sqltypes/sqltypes.go
Adding changes needed for handling sql UTF8 marshaling/unmarshaling and allowing reading values from SQL if they are nullable. This can happen sometimes if the tables get new columns and some of the items are left nullable. Default values are expected in this case, which is what's expected.
=> - Adding Utf8String and ConverAssignRowNullable

resource_pool/simple_resource_pool.go
dial timeout err string doesn't include the location
=> better connection pool error msg

database/sqlbuilder/statement.go, database/sqlbuilder/statement_test.go
Specifically added:
WHERE
(AND where)
GROUP BY
ORDER BY
LIMIT (and offset)
This also adds back in parentheses to the selects comprising the union select statement, allowing you to use order by and limit in the inner statements.
=> Add support additional for clauses in Union Selects in SQLBuilder

rate_limiter/rate_limiter.go
=> Fix QuotaPerSec bug in rate_limiter constructor

resource_pool/simple_resource_pool.go, resource_pool/simple_resource_pool_test.go
=> Fix off by one error in resource pool when freeing idle connections

container/concurrent/lockstore/all_test.go, container/concurrent/lockstore/lock.go, container/concurrent/lockstore/map.go, container/concurrent/lockstore/map_test.go, container/concurrent/lockstore/store.go, container/concurrent/lockstore/store_test.go, lockstore/all_test.go, lockstore/lock.go, lockstore/map.go, lockstore/map_test.go, lockstore/store.go, lockstore/store_test.go
I'm not sure what the protocol is for this, but I removed the BUILD file since it seems we don't build with bazel out here.
=> Adding lockstore/ from repo

database/binlog/previous_gtid_log_event_test.go, executor/executor_test.go, memcache/raw_ascii_client.go, memcache/sharded_client_test.go, net2/http2/load_balanced_pool_test.go, net2/http2/simple_pool.go, resource_pool/simple_resource_pool.go
* remove types if can be elided
* gofmt for missing files
* gofmt will remove optional blank identifier in range but kept it
=> all: gofmt simplify

cinterop/test/client.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
=> delete minor unreachable code caused by log.Fatal
